apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: k8sgpt-frontend-settings
  envs:
  - settings.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.INGRESS_HOSTNAME
  targets:
  - select:
      kind: Certificate
      name: k8sgpt-frontend-cert
    fieldPaths:
    - spec.dnsNames.0
  - select:
      kind: Gateway
      name: k8sgpt-frontend-gateway
    fieldPaths:
    - spec.listeners.0.hostname
    - spec.listeners.1.hostname
  - select:
      kind: HTTPRoute
      name: k8sgpt-frontend-http-redirect
    fieldPaths:
    - spec.hostnames.0
  - select:
      kind: HTTPRoute
      name: k8sgpt-frontend-https
    fieldPaths:
    - spec.hostnames.0
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.CERT_ISSUER
  targets:
  - select:
      kind: Certificate
      name: k8sgpt-frontend-cert
    fieldPaths:
    - spec.issuerRef.name
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.IMAGE
  targets:
  - select:
      kind: Deployment
      name: k8sgpt-frontend
    fieldPaths:
    - spec.template.spec.containers.0.image
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.APPRISE_URL
  targets:
  - select:
      kind: Deployment
      name: k8sgpt-frontend
    fieldPaths:
    - spec.template.spec.containers.0.env.0.value
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.UI_URL
  targets:
  - select:
      kind: Deployment
      name: k8sgpt-frontend
    fieldPaths:
    - spec.template.spec.containers.0.env.1.value
- source:
    kind: ConfigMap
    name: k8sgpt-frontend-settings
    fieldPath: data.POLL_INTERVAL
  targets:
  - select:
      kind: Deployment
      name: k8sgpt-frontend
    fieldPaths:
    - spec.template.spec.containers.0.env.2.value
